### ISSUE TITLE
schematic placements crash game.

### ISSUE THREAD

**Issue by zLauch** [End-Tech/syncmatica#23]
if i go with the newest version (0.2.2) into schematic placements my game crashes.
i tryed to older version (0.1.1) and it worked fine.
[crash-2021-05-19_01.13.23-client.txt](https://github.com/End-Tech/syncmatica/files/6504879/crash-2021-05-19_01.13.23-client.txt)

EDIT: server is also on v.0.2.2

**Comment by zLauch** [comment]
litematica version: v0.0.0-dev.20210106.181551

**Comment by nnnik** [comment]
You may want to update and try again.
Its possible that the mappings I used provide access to methods that are not available in your version of the mod.

**Comment by nnnik** [comment]
Does it work now?

**Comment by nnnik** [comment]
Ill consider this
