### ISSUE TITLE
Syncmatica issue

### ISSUE THREAD

**Issue by igneousrock47** [End-Tech/syncmatica#24]
![Jre-legacy Screenshot 2021 06 07 - 15 13 30 93](https://user-images.githubusercontent.com/85503805/121036040-56d17c00-c7a6-11eb-90b7-3dcfbbf2079a.png)

as you see in the image the view syncmatics button and material collections buttons are blank, i cant share schematics  and my friend has the same problem

what do i do?

**Comment by nnnik** [comment]
The mod needs to be installed on the server and the version on the server needs to be compatible with the version on the client.
The MaterialGatherings button is a planned feature - I got too far ahead and added it too early. 
Another problem may be that a mod interferes with syncmaticas method of communication - like older versions of multi connect.
If this doesn't help you I need some extra information on what is going on with the server and client

**Comment by igneousrock47** [comment]
> The mod needs to be installed on the server and the version on the server needs to be compatible with the version on the client.
> The MaterialGatherings button is a planned feature - I got too far ahead and added it too early.
> Another problem may be that a mod interferes with syncmaticas method of communication - like older versions of multi connect.
> If this doesn't help you I need some extra information on what is going on with the server and client

ight first of all thank you for reaching out, so i run the server off my pc, we play on 1.16.5 both client (for sure) and server (i think). Also id like to point out that we had this work before but one day it suddenly stopped working. excuse my lack of knowledge on github ive never used it.

**Comment by nnnik** [comment]
Which version do you have on your Client and which version do you have on your server?
What is the mod loader that you use. 
What other mods do you have on the server/client

**Comment by igneousrock47** [comment]
> Which version do you have on your Client and which version do you have on your server? both 1.16.5
> What is the mod loader that you use. fabric 
> What other mods do you have on the server/client  server-syncmatica only and then for me client side in my mods folder- fabric api, optifabric, optifine, syncmatica, malilib fabric

**Comment by nnnik** [comment]
Hmm that seems very weird.
How do you start the server? 
Is it like its full own dedicated server?
If it is I will probably need to add some debug messages to see whats going on

**Comment by igneousrock47** [comment]
yes this is my server and i start it, its not 24/7 i just play when me and my friends want to

**Comment by nnnik** [comment]
Hey sorry for the long delay.
Here is a version that logs some additional information when you connect to the server.
You can install this on the server and client and then send me both the debug output logs so that I can see whats going on.
I just need to see the initial connection as Syncmatica handles its own connection there and that is the step that appears to fail.

https://minecraftirc.net/support-articles/get-minecraft-log/ this is how you get them for the client.
If you need further help with getting logs for the server or client feel free to let me know.

**Comment by nnnik** [comment]
With here I mean the latest release:
https://github.com/End-Tech/syncmatica/releases/tag/v0.2.4

**Comment by igneousrock47** [comment]
hey yeah i need help with getting the logs for the server

i think i have the client logs :
20:30:22.902
Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
20:30:22.903
[OptiFine] Animated sprites: 0
20:30:23.558
Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
20:30:23.588
[OptiFine] Animated sprites: 0
20:30:23.589
Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
20:30:23.591
[OptiFine] Animated sprites: 0
20:30:23.591
Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
20:30:23.591
[OptiFine] Animated sprites: 0
20:30:23.592
[OptiFine] *** Reloading custom textures ***
20:30:23.593
[OptiFine] Sprite not found: minecraft:block/grass_block_side_overlay
20:30:23.597
[OptiFine] Unknown resource pack type: net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack@75a46b
20:30:23.666
[OptiFine] Unknown resource pack type: net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack@19f7179
20:30:23.744
[OptiFine] CustomColors: Loading optifine/color.properties
20:30:23.745
[OptiFine] Unknown resource pack type: net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack@2ac974bc
20:30:26.011
[OptiFine] Unknown resource pack type: net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack@7bbdaf51
20:30:26.283
[OptiFine] Unknown resource pack type: net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack@7ad6b9b2

**Comment by nnnik** [comment]
Hmm they should be longer - Im mainly interested in the Syncmatica portion.
I also get the feeling that github may not be the proper mode of communication and that we need a more direct connection.
Do you have any other forms of communication?

**Comment by igneousrock47** [comment]
yes add me on discord its an alt for privacy's sake - Sedimentary rock#1137

**Comment by nnnik** [comment]
https://discord.gg/nTxwfb7Z
Since you apparently ned to share a discord server I just made a new server.

**Comment by nnnik** [comment]
Issue has been fixed over discord - some configuration issues on the minecraft server and how it was launched caused it
