### ISSUE TITLE
Is there a way to Join a 1.16.5 server on 1.16.5 server with multiconnect and have syncmatica work?

### ISSUE THREAD

**Issue by JacktheDevel0per** [End-Tech/syncmatica#30]

**Comment by nnnik** [comment]
Hey Jack - sorry for the late response.
I have been moving recently.
I sadly do not know what Multiconnect does to mess with other mods.
Last time I checked there were no issues with multiconnect on newer Versions so I suggest updating Milticonnect.
On earlier Versions Multiconnect ate all incoming packets and expected all other mods in the world to register its connector.
I personally do not see the point nor do I want to put in the work to maintain a connection to a 3rd mod that now functions properly.
If there are new incompatabilities with the Multiconnect mod I will check it out.
The old incompatability however is something you need Multiconnect to fix.
Anyone can also make a mod that "fixes" Multiconnect by directly removing the problematic functionality from it.

**Comment by JacktheDevel0per** [comment]
Yes and no, I was wondering because I have a different version of sync then is there any backward compat, but I'm fine now I changed versions and the server is about to update

**Comment by nnnik** [comment]
All versions of syncmatica are compatible except 0.1.0.
You will miss out on some features if you use an older version of syncmatica either on the server or the client.
There is no need to handle Updating syncmatica in any special way.
As long as the litematica version that you move to is able to load the litematics of the old version it should be as easy as just putting in the new version

**Comment by nnnik** [comment]
I guess this should be closed then
