### ISSUE TITLE
When sharing a schematic, it gives an error

### ISSUE THREAD

**Issue by QPCrummer** [End-Tech/syncmatica#34]
Here is the error: https://pastebin.com/xS9gyta0

Here is my mods listhttps://pastebin.com/wTT7NgCx

My server is running 1.17.1 Quilt

**Comment by QPCrummer** [comment]
Also, it actually never shares the schematic

**Comment by nnnik** [comment]
Hi I'm unsure why that happens but the server appears to be complaining that it cannot talk to the client.
I will look into it but I need a little more information - can you try it with fabric and can you try to remove all other mods and run it with quilt to see if it works?

**Comment by nnnik** [comment]
So it looks to me like the client failed to verify themselves to the server.
Which version of syncmatica is the client using?

**Comment by QPCrummer** [comment]
same as the server, 0.2.6

**Comment by nnnik** [comment]
Hmm can you enable debugging on both the client and the server and send me the logs?
See the documentation for reference.

**Comment by nnnik** [comment]
Does this still happen after v0.3.0?

**Comment by QPCrummer** [comment]
@nnnik Seems to be working just fine!
