### ISSUE TITLE
It appears that you cannot use syncmatica in LAN

### ISSUE THREAD

**Issue by XTremeFucc** [End-Tech/syncmatica#35]
My guess would be that the mod thinks I'm in singleplayer so it disables the feature

All mods should be compatible with each other and it didn't seem like any of them were causing this to happen (below are mods I use)

![image](https://user-images.githubusercontent.com/95578252/147858986-ca2e2f2e-96ce-41ff-9108-07739a85046e.png)

Not really a very important issue but would be nice to see LAN compatibility of some sort

**Comment by nnnik** [comment]
It doesnt start a server on the client when the client is in single player. That feature simply isnt implemented yet.
I made a lot of changes to the backend in one of the recent versions to allow the starting of a server even when a client environment is present

**Comment by nnnik** [comment]
Should work now
