### ISSUE TITLE
My friends can't see blueprints I've placed.

### ISSUE THREAD

**Issue by whitecat346** [End-Tech/syncmatica#42]
Hi, I have this mod installed on my server, and my friend and I both have this mod installed, but my friend can't see the blueprint I placed.（Since I don't speak English, I use translation software. I'm sorry if you don't understand what I'm talking about.）

**Comment by nnnik** [comment]
Hi - is this issue still there?
Also did your friend check the Syncmatics Window?
Did your share your placement?

**Comment by whitecat346** [comment]
My problem has been solved,thx。

**Comment by nnnik** [comment]
Alright thank you for your response :)
