### ISSUE TITLE
`0.3.6` causes my `1.19.2` server to not start

### ISSUE THREAD

**Issue by ChristopherHaws** [End-Tech/syncmatica#46]
After updating to 0.3.6 my server no longer starts. Downgrading back to 0.3.5 fixes the issue.

Here are my server logs:
https://mclo.gs/q9mFMtE

**Comment by gniftygnome** [comment]
class_1132 is net/minecraft/server/integrated/IntegratedServer so this is probably a missed guard against doing integrated server stuff when running on a multiplayer server.  I've got basically the same error with a very different set of mods.

**Comment by gniftygnome** [comment]
Oh, it's an instanceof call.

```java
        Syncmatica.initServer(
                new ServerCommunicationManager(),
                new FileStorage(),
                new SyncmaticManager(),
                returnValue instanceof IntegratedServer,
                returnValue.getSavePath(WorldSavePath.ROOT).toFile()
        ).startup();
```

I think in 1.19+ at least it's intended to use `!returnValue.isDedicated()` rather than `returnValue instanceof IntegratedServer` although I've not needed to check dedicated vs. integrated before.

**Comment by nnnik** [comment]
Thank you for this report I will try to fix

**Comment by nnnik** [comment]
That seems to be indeed the problem. 1.19 makes the DedicatedServer class client only.
isDedicated is indeed what I want here.

**Comment by nnnik** [comment]
I apologize for the delay on this one - I have setup webhooks to the Discord now to get notified of issues like these quicker.
Please check out the latest releases for a fix.
https://github.com/End-Tech/syncmatica/releases/tag/v0.3.7-1.16.5
