### ISSUE TITLE
v0.3.8-1.18.2 Marked as Forge mod

### ISSUE THREAD

**Issue by Drhampust** [End-Tech/syncmatica#51]
The latest release on curseforge is marked as a Forge mod which in turns stops Curseforge from finding compatible version when adding mods to your modpack.
Alsos causes incompatible mod warning whilst manually added.

Guessing that this is wrong as the mod works for 1.19.3 Fabric.
![image](https://user-images.githubusercontent.com/30093870/215323704-f6ebff1e-148d-4d1a-a827-5e6b2ff12c4e.png)

**Comment by nnnik** [comment]
Thanks for the hint. It's fixed now
