### ISSUE TITLE
ETA of 1.20(.1)?

### ISSUE THREAD

**Issue by Mudxiej** [End-Tech/syncmatica#57]
Just let us know if you are working at least for it. Give me a hope for this mod

**Comment by nnnik** [comment]
1.20 and 1.20.1 are already out...

**Comment by Mudxiej** [comment]
> 1.20 and 1.20.1 are already out...

huh? where i cant seem find it

**Comment by Mudxiej** [comment]
> > 1.20 and 1.20.1 are already out...
> 
> huh? where i cant seem find it

i take it back - it's on modrinth page
