### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by sakura-ryoko** [End-Tech/syncmatica#63]
Hello,  I have attempted to port the mod myself, but ran into Custom C2S/S2C Payload (net.minecraft.network.packet.c2s.common.CustomPayloadC2SPacket) issues that I don't know how to fix.
Thanks! :)

**Comment by nnnik** [comment]
I don't have the energy to look at it right now.
I will hand in an assignment next week after that I will come back to you.
Otherwise feel free to message me on discord :).

**Comment by sakura-ryoko** [comment]
Check out this fork, they seem to have fixed some of the issues I was referring to, but I haven't tried it:
https://github.com/End-Tech/syncmatica/compare/master...jSdCool:syncmatica:1.20.2

**Comment by jSdCool** [comment]
I am current running into an issue where when a client connects they get immediately disconnected because a packed contained 37 more bytes then expected. or an unsupported operation occurred.
no idea why this is happening.

**Comment by sakura-ryoko** [comment]
Yeah interesting code but I am looking around at other mods and they are completely ditching the "CustomPayloadC2SPacket" handler based code.  Take a look at this DIFF for ServUX for example:
https://github.com/maruohon/servux/commit/40c87cdd4c254b31ba1187eb4251f4e6d02446aa#diff-8b2b4dc2beddf33f175067672b99fa8dcd3900d5283846b3077fc01274f94546

**Comment by nnnik** [comment]
Yeah I will probably ditch it too and go even further and remove PacketByteBuf too for my own implementation.

**Comment by sakura-ryoko** [comment]
Yeah the GUI and everything was working fine using masa's current litematica code, just the "Share" and "View Schematics" buttons were greyed out.  Also the fabric.mod.json needed a few extra lines for version numbers instead of "*" ... it kept whining about that and failed to load the mod without it, but in terms of lazy porting I think I understand that work flow at least!  :)

**Comment by jSdCool** [comment]
The reason it was saying "Unknown Identifier syncmatica:payload" is most likely because in 1.20.2 the supported types of custom payloads are hard coded into the C2S and S2C classes.   I used a mixin in my attempt to bypass this hard coding.

 I think Ditching the Custom Payload packs might be a good idea.

**Comment by nnnik** [comment]
See the thing is syncmatica 0.3.10 can still communicate with syncmatica 0.2.0. I have invested a lot of code into making this work.
I'd rather stop developing altogether than moving away from C2S and S2C packets.

**Comment by sakura-ryoko** [comment]
It might still work if the "unknown identifier" part is resolved ... idk

**Comment by Adogs1** [comment]
所以syncmatica1.20.2无法更新了？
